### PR TITLE
Install maxima into ecl directory

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
@embray, do you know why `binary_ecl/maxima.fas` is not generated?

**Comment by embray** [comment]
I don't know. I can look into it. This is why I originally removed this part but I guess it is needed after all. I don't full understand though.

**Comment by isuruf** [comment]
Maybe we need this patch, https://github.com/sagemath/sage/blob/master/build/pkgs/maxima/patches/build-fasl.patch

**Comment by isuruf** [comment]
Without installing maxima into ecl, sage doesn't work because sage calls maxima through ecl

**Comment by embray** [comment]
Thanks--looks to me like the issue there was the patch the I originally had but removed, thinking it wasn't needed except for building in sage, which is clearly my misunderstanding.

**Pull request merged**
